/* common constants*/

const MESSAGE_KEY_WEIGHTS_RETREIVED_API = "WEIGHTS_FROM_WEB";
const MESSAGE_KEY_SETTINGS_UNIT = "UNIT";
const MESSAGE_KEY_WEIGHT_POSTED_API = "WEIGHTS_TO_WEB";

export {
    MESSAGE_KEY_SETTINGS_UNIT,
    MESSAGE_KEY_WEIGHT_POSTED_API,
    MESSAGE_KEY_WEIGHTS_RETREIVED_API
};