/* common constants*/
const SETTINGS_KEY_OAUTH = "OAUTH";
const SETTINGS_KEY_UNIT = "UNIT";

const MESSAGE_RECEIVED_WEIGHT_LOG_API = "RECEIVED_FROM_WEB";
const MESSAGE_REQUEST_WEIGHT_LOG_API = "REQUEST_FROM_WEB"
const MESSAGE_POST_WEIGHTS_API = "POST_TO_WEB";
const MESSAGE_POST_SUCCESS_API = "SUCCESS_POST_TO_WEB";
const MESSAGE_UNIT_SETTING_CHANGED = SETTINGS_KEY_UNIT;

export {
    MESSAGE_UNIT_SETTING_CHANGED,
    MESSAGE_POST_SUCCESS_API,
    MESSAGE_POST_WEIGHTS_API,
    MESSAGE_RECEIVED_WEIGHT_LOG_API,
    MESSAGE_REQUEST_WEIGHT_LOG_API,
    SETTINGS_KEY_OAUTH,
    SETTINGS_KEY_UNIT
};